# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/ERN24004/Projects/ADC/ADC.srcs/sources_1/bd/dma/ip/dma_PmodAD1_0_1/dma_PmodAD1_0_1.xci
# IP: The module: 'dma_PmodAD1_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/ERN24004/Projects/ADC/ADC.gen/sources_1/bd/dma/ip/dma_PmodAD1_0_1/src/pmod_bridge_0/pmod_bridge_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_bridge_0 || ORIG_REF_NAME==pmod_bridge_0} -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/ADC/ADC.gen/sources_1/bd/dma/ip/dma_PmodAD1_0_1/src/pmod_bridge_0/pmod_bridge_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pmod_bridge_0 || ORIG_REF_NAME==pmod_bridge_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/ADC/ADC.gen/sources_1/bd/dma/ip/dma_PmodAD1_0_1/src/pmod_bridge_0/src/pmod_concat_ooc.xdc

# XDC: c:/Projects/ERN24004/Projects/ADC/ADC.gen/sources_1/bd/dma/ip/dma_PmodAD1_0_1/dma_PmodAD1_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_PmodAD1_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Projects/ERN24004/Projects/ADC/ADC.srcs/sources_1/bd/dma/ip/dma_PmodAD1_0_1/dma_PmodAD1_0_1.xci
# IP: The module: 'dma_PmodAD1_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Projects/ERN24004/Projects/ADC/ADC.gen/sources_1/bd/dma/ip/dma_PmodAD1_0_1/src/pmod_bridge_0/pmod_bridge_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pmod_bridge_0 || ORIG_REF_NAME==pmod_bridge_0} -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/ADC/ADC.gen/sources_1/bd/dma/ip/dma_PmodAD1_0_1/src/pmod_bridge_0/pmod_bridge_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pmod_bridge_0 || ORIG_REF_NAME==pmod_bridge_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Projects/ERN24004/Projects/ADC/ADC.gen/sources_1/bd/dma/ip/dma_PmodAD1_0_1/src/pmod_bridge_0/src/pmod_concat_ooc.xdc

# XDC: c:/Projects/ERN24004/Projects/ADC/ADC.gen/sources_1/bd/dma/ip/dma_PmodAD1_0_1/dma_PmodAD1_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_PmodAD1_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
